### PR TITLE
Orfox tor browser 38.5.0esr 5.5 2

### PR DESCRIPTION
**Pull request by amoghbl1**
Orfox update to 38.5.0esr.
Might want to make a new branch for this, please ask me if you need another PR.

### CODE REVIEW

**Comment by n8fr8** [comment]
There are a lot of conflicts to resolve... this is taking awhile...

**Comment by amoghbl1** [comment]
OK, I think this is easier if you just pull my branch in, or if I open this PR against the tor-browser-38.5.0esr-5.5-2 branch.
I don't have write access on this repo, so I can't create a branch... If you could do that, I'll open another PR.

**Comment by n8fr8** [comment]
Right. I will just pull in your branch. Sometimes git is so frustrating. I don't know why it can't auto-resolve the conflicts that are coming up anyhow.

**Comment by n8fr8** [comment]
Okay I merged everything and pushed it here:
https://github.com/guardianproject/tor-browser/tree/orfox-tor-browser-38.5.0esr-5.5-2

**Pull request closed without merging**
